services:
  goof:
    image: nodejs-goof:${BUILD_NUMBER}
    container_name: goof-production
    environment:
      - DOCKER=1
    ports:
      - "3002:3001"
    depends_on:
      - goof-mongo
  goof-mongo:
    container_name: goof-mongo-production
    image: mongo:3
    ports:
      - "27018:27017"